import { execFileSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "..")
const pkg = path.join(root, "rust", "pkg")
const out = path.join(root, "wasm")

execFileSync("wasm-pack", ["build", "--target", "web", "--release", "--features", "wasm"], {
  cwd: path.join(root, "rust"),
  stdio: "inherit",
  shell: process.platform === "win32"
})

fs.mkdirSync(out, { recursive: true })
fs.copyFileSync(path.join(pkg, "block_model_renderer.js"), path.join(out, "block_model_renderer.js"))
fs.copyFileSync(path.join(pkg, "block_model_renderer.d.ts"), path.join(out, "block_model_renderer.d.ts"))

// the bundle is one file served from a cdn and also runs inside workers, so the
// module travels with it rather than as a second fetch
const bytes = fs.readFileSync(path.join(pkg, "block_model_renderer_bg.wasm"))
fs.writeFileSync(
  path.join(out, "inline.js"),
  `// generated by tools/build-wasm.js\nexport const WASM_BASE64 = "${bytes.toString("base64")}"\n`
)

console.log(`wasm: ${(bytes.length / 1024).toFixed(1)}KB -> inline.js ${(bytes.length * 4 / 3 / 1024).toFixed(1)}KB base64`)
